export class IEnrollment { 
    _id: string;
    packs: string[];
    host_details:{ 
        os_version:{ 
           build:string,
           major:string,
           minor:string,
           name:string,
           patch:string,
           platform:string,
           platform_like:string,
           version:string
        },
        osquery_info:{ 
           build_distro:string,
           build_platform:string,
           config_hash:string,
           config_valid:string,
           extensions:string,
           instance_id:string,
           pid:string,
           start_time:string,
           uuid:string,
           version:string,
           watcher:string
        },
        platform_info:{ 
           address:string,
           date:string,
           extra:string,
           revision:string,
           size:string,
           vendor:string,
           version:string,
           volume_size:string
        },
         system_info: { 
            computer_name:string,
            cpu_brand:string,
            cpu_logical_cores:string,
            cpu_physical_cores:string,
            cpu_subtype:string,
            cpu_type:string,
            hardware_model:string,
            hardware_serial:string,
            hardware_vendor:string,
            hardware_version:string,
            hostname:string,
            local_hostname:string,
            physical_memory:string,
            uuid:string
        }
    }
};
